const HTTP_STATUS = {
  OK: 200,
  BAD_REQUEST: 400,
  SERVICE_UNAVAILABLE: 503,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

const CONTENT_TYPE_JSON = "application/json; charset=utf-8";
const ERROR_CODES = {
  INVALID_INGEST_ID: "INVALID_INGEST_ID",
  INGESTION_THREAD_UNAVAILABLE: "INGESTION_THREAD_UNAVAILABLE",
  INGESTION_THREAD_MESSAGE_FAILED: "INGESTION_THREAD_MESSAGE_FAILED",
  INGESTION_THREAD_CRASHED: "INGESTION_THREAD_CRASHED",
  INVALID_CLUSTER_MESSAGE: "INVALID_CLUSTER_MESSAGE",
  WORKER_IPC_SEND_FAILED: "WORKER_IPC_SEND_FAILED",
  SERVER_LISTEN_FAILED: "SERVER_LISTEN_FAILED",
  SERVER_CLOSE_FAILED: "SERVER_CLOSE_FAILED",
  ROUTE_EXECUTION_FAILED: "ROUTE_EXECUTION_FAILED",
};

module.exports = {
  HTTP_STATUS,
  CONTENT_TYPE_JSON,
  ERROR_CODES,
};
